#!/bin/bash
#
# This script of pre-push is for not forget to upload an cookbook into chef server
#
# version: 0.0.1
# author: Roberto Scudeller
# 
#

FILES=$(find . -type f ! -name ".git*" ! -name ".kitchen*" |egrep -v "git|kitchen|chefignore|Berksfile.lock")

  cookbook=$( echo "$FILES"|grep "metadata.rb" |cut -f2 -d"'" )
  cookbook_name=$( grep name $cookbook |cut -f2 -d"\""|cut -f2 -d"'" )
  if [[ "${PWD}" == *cookbooks* ]]; then
    read -p "Do you want update the cookbook into chef server? Ex.: knife cookbook upload $cookbook_name  (y/N)" -n 2 -r < /dev/tty
    case $REPLY in
      [YySs]*) 
        echo "running: knife cookbook upload $cookbook_name"
        knife cookbook upload $cookbook_name
      ;;
      *)
        echo "skipping...run: knife cookbook upload $cookbook_name "
        exit 0 ;;
    esac     
  fi

exit 0
